first_number = int(input("what is ur first number?"))
second_number = int(input("wht is ur second number"))
print(first_number + second_number)
print(first_number - second_number)
print(first_number / second_number)
print(first_number * second_number)
print(first_number // second_number)
print(first_number % second_number)
print(first_number ** second_number)
print(first_number > second_number)
print(first_number == second_number)
